LifeForce/Manifest/unpackaged/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GC1040</fullName>
                </value>
                <value>
                    <fullName>GC1060</fullName>
                </value>
                <value>
                    <fullName>GC3020</fullName>
                </value>
                <value>
                    <fullName>GC3040</fullName>
                </value>
                <value>
                    <fullName>GC3060</fullName>
                </value>
                <value>
                    <fullName>GC5020</fullName>
                </value>
                <value>
                    <fullName>GC5040</fullName>
                </value>
                <value>
                    <fullName>GC5060</fullName>
                </value>
                <value>
                    <fullName>GC1020</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

LifeForce/Manifest/unpackaged/objects/Product_Interest__c.object
<CustomObject>
    <description>Products that is of interest to the lead.</description>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Product Interests</relationshipLabel>
        <relationshipName>Product_Interests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Interests</relationshipLabel>
        <relationshipName>Product_Interests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Interest</label>
    <nameField>
        <displayFormat>L{00}P{00}</displayFormat>
        <label>Product Interest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Interests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LifeForce/Manifest/unpackaged/objects/Product_Selection__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Product Selections</relationshipLabel>
        <relationshipName>Product_Selections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Selections</relationshipLabel>
        <relationshipName>Product_Selections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Selection</label>
    <nameField>
        <label>Product Selection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Selections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LifeForce/Manifest/unpackaged/classes/Test_Service_AddProduct.cls
@isTest
public class Test_Service_AddProduct {
    
    @isTest
    public static void testGetProduct(){
        // insert product
        Product2 prod = new Product2();
        prod.Name='SLA: Gold';
        insert prod;
        // call on a method and query
        test.startTest();
        List<Product2> listProd = ProductSelectionController.getProducts('SLA');
        System.assert(listProd.size()>0);
        test.stopTest();
        
    }
    
    @isTest
    public static void testAddToCase(){
        Case c = new Case();
        c.Status = 'New';
        c.Origin = 'Email';
        insert c;
        String parentId = c.Id;
        
        Product2 prod = new Product2();
        prod.Name='SLA: Gold';
        List<String> listProdIds = new List<String>();
        listProdIds.add(prod.Id);
        insert Prod;
        
        Product_Selection__c ps = new Product_Selection__c();
        ps.Name = 'Test';
        ps.Case__c = c.Id;
        ps.Product__c = prod.Id;
        insert ps; 
        
        test.startTest();
        ProductSelectionController.addProdToCase(parentId, listProdIds);
        System.assertEquals(2,[SELECT Id FROM Product_Selection__c].size());
        test.stopTest();
    }
    
    @isTest
    public static void testAddToLead(){
        Lead l = new Lead();
        l.LastName = 'New';
        l.Company = 'Email';
        l.Status = 'Open - Not Contacted';
        insert l;
        String parentId = l.Id;
        
        Product2 prod = new Product2();
        prod.Name='SLA: Gold';
        List<String> listProdIds = new List<String>();
        listProdIds.add(prod.Id);
        insert Prod;
        
        Product_Interest__c pi = new Product_Interest__c();
        pi.Lead__c = l.Id;
        pi.Product__c = prod.Id;
        insert pi; 
        
        test.startTest();
        ProductSelectionController.addProdToLead(parentId, listProdIds);
        System.assertEquals(2,[SELECT Id FROM Product_Interest__c].size());
        test.stopTest();
    }
    
}