LifeForce/Manifest/unpackaged/objects/Product_Interest__c.object
<CustomObject>
    <description>Products that is of interest to the lead.</description>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Product Interests</relationshipLabel>
        <relationshipName>Product_Interests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Interests</relationshipLabel>
        <relationshipName>Product_Interests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Interest</label>
    <nameField>
        <displayFormat>L{00}P{00}</displayFormat>
        <label>Product Interest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Interests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LifeForce/Manifest/unpackaged/objects/Product_Selection__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Product Selections</relationshipLabel>
        <relationshipName>Product_Selections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Selections</relationshipLabel>
        <relationshipName>Product_Selections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Selection</label>
    <nameField>
        <label>Product Selection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Selections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

LifeForce/Manifest/unpackaged/classes/ProductSelectionController.cls
public class ProductSelectionController {
        
        @AuraEnabled
        public static List<Product2> getProducts(String searchKeyword){
            String searchKey = searchKeyword + '%';
            List<Product2> prodList = new List<Product2>();
            List<Product2> result = Database.query('SELECT Id, Name FROM Product2 WHERE Name LIKE : searchKey LIMIT 50');
                for (Product2 p : result){    
                    prodList.add(p);
                }
                return prodList;
            }
            
            @AuraEnabled
            public static void addProdToCase (String ParentId, List<String> listProdIds){        
                List<Product_Selection__c> listProds = new List<Product_Selection__c>();
                for(String prodId : listProdIds){
                    Product_Selection__c prod = new Product_Selection__c();
                    prod.Product__c = prodId;
                    prod.Case__c = ParentId;
                    listProds.add(prod);
                }
                insert listProds;
            }
            
            @AuraEnabled
            public static void addProdToLead (String ParentId, List<String> listProdIds){        
                List<Product_Interest__c> listProds = new List<Product_Interest__c>();
                for(String prodId : listProdIds){
                    Product_Interest__c prod = new Product_Interest__c();
                    prod.Product__c = prodId;
                    prod.Lead__c = ParentId;
                    listProds.add(prod);
                }
                insert listProds;
            }
            
        }