LifeForce/Manifest/unpackaged/objects/Product_Interest__c.object
<CustomObject>
    <description>Products that is of interest to the lead.</description>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Product Interests</relationshipLabel>
        <relationshipName>Product_Interests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Product Interests</relationshipLabel>
        <relationshipName>Product_Interests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product Interest</label>
    <nameField>
        <displayFormat>L{00}P{00}</displayFormat>
        <label>Product Interest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Interests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LifeForce/Manifest/unpackaged/classes/LeadTriggerHandler.cls
public with sharing class LeadTriggerHandler {
    
    public void handleConvertedLeads(List<Lead> convertedLeads){
        //get products related to converted leads
        List<Product_Interest__c> relatedProducts = [SELECT Name,Product__r.id,Lead__r.id, Lead__r.convertedOpportunityId 
                                                     FROM Product_Interest__c
                                                     WHERE Lead__r.id IN :convertedLeads];
        //list of products to insert into opp line item
        List<OpportunityLineItem> itemsToInsert = new List<OpportunityLineItem>();
        
        
        //loop through related product and store it into a opporutuniy Line Item list
        // with opp id and product id
        for(Product_Interest__c prodInterest: relatedProducts ){
            
            OpportunityLineItem oppProduct = new OpportunityLineItem(OpportunityId = prodInterest.Lead__r.convertedOpportunityId, Product2Id = prodInterest.Product__c, Quantity = 1, TotalPrice = 100 );
            itemsToInsert.add(oppProduct);
            
        }
        // 
        if(itemsToInsert.size() > 0)
        	insert itemsToInsert;
    }
    
}